/**
 * Numerical parity test: does the TypeScript port (realModel.ts) reproduce
 * PyTorch's forward() bit-for-bit (to float32 tolerance) on the same weights
 * and input? This is the test described in the project's own brief §20/§21 —
 * "create comparison tests" against the reference implementation, "don't
 * assume visually similar means scientifically equivalent."
 *
 * The fixture (web/frontend/public/model/fixture_*.bin) was generated by
 * web/export/export_model_bundle.py: real abiotic + land mask for the
 * checkpoint's config, fixed-seed random biotic/detection_history (full
 * grid, not cropped, so replicate-padding behavior at the true grid edges
 * is exercised exactly as PyTorch saw it), and the actual PyTorch output.
 *
 * Run (from web/frontend):
 *   npm run test:parity                          # tests model/no_detection_history (default)
 *   npm run test:parity -- with_detection_history # tests any other exported model subfolder
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { RealNeuralLandscapeModel, type RealModelManifest } from "../realModel.ts";
import type { GridContext, SimState } from "../types.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const modelName = process.argv[2] ?? "no_detection_history";
const MODEL_DIR = path.resolve(__dirname, "../../../public/model", modelName);

function readF32(name: string): Float32Array {
  const buf = readFileSync(path.join(MODEL_DIR, name));
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
}

function splitChannels(flat: Float32Array, nChannels: number, cellsPerChannel: number): Float32Array[] {
  return Array.from({ length: nChannels }, (_, c) =>
    flat.subarray(c * cellsPerChannel, (c + 1) * cellsPerChannel)
  );
}

function main(): void {
  const manifest: RealModelManifest = JSON.parse(
    readFileSync(path.join(MODEL_DIR, "model.json"), "utf-8")
  );
  const { gridH, gridW, nAbiotic, nSpecies, speciesNames } = manifest;
  const cells = gridH * gridW;
  console.log(`Model: ${manifest.modelId} (${gridH}x${gridW}, ${nSpecies} species, ${nAbiotic} abiotic)`);

  const model = RealNeuralLandscapeModel.fromBuffers(
    manifest,
    readF32("conv1_weight.bin"),
    readF32("conv1_bias.bin"),
    readF32("conv2_weight.bin")
  );

  const abiotic = splitChannels(readF32("fixture_abiotic.bin"), nAbiotic, cells);
  const landMaskF32 = readF32("fixture_land_mask.bin");
  const landMask = Uint8Array.from(landMaskF32, (v) => (v > 0 ? 1 : 0));
  const biotic = splitChannels(readF32("fixture_biotic_in.bin"), nSpecies, cells);
  const detectionHistory = splitChannels(readF32("fixture_det_history_in.bin"), nSpecies, cells);
  const expected = splitChannels(readF32("fixture_biotic_out_expected.bin"), nSpecies, cells);

  const ctx: GridContext = { gridH, gridW, landMask, abiotic };
  const state: SimState = { biotic, detectionHistory };

  const t0 = performance.now();
  const result = model.step(state, ctx);
  const elapsedMs = performance.now() - t0;

  const TOLERANCE = 1e-4;
  let worstMaxDiff = 0;
  let anyFail = false;
  console.log(`\nstep() took ${elapsedMs.toFixed(1)}ms\n`);
  console.log("species".padEnd(24), "maxDiff".padStart(12), "meanDiff".padStart(12), "status");
  for (let s = 0; s < nSpecies; s++) {
    const got = result.biotic[s];
    const want = expected[s];
    let maxDiff = 0;
    let sumDiff = 0;
    for (let i = 0; i < cells; i++) {
      const d = Math.abs(got[i] - want[i]);
      if (d > maxDiff) maxDiff = d;
      sumDiff += d;
    }
    const meanDiff = sumDiff / cells;
    const pass = maxDiff <= TOLERANCE;
    if (!pass) anyFail = true;
    if (maxDiff > worstMaxDiff) worstMaxDiff = maxDiff;
    console.log(
      speciesNames[s].padEnd(24),
      maxDiff.toExponential(3).padStart(12),
      meanDiff.toExponential(3).padStart(12),
      pass ? "PASS" : "FAIL"
    );
  }

  console.log(`\nworst max diff across all species: ${worstMaxDiff.toExponential(3)} (tolerance ${TOLERANCE})`);
  if (anyFail) {
    console.error("\nPARITY TEST FAILED — TS port does not match PyTorch within tolerance.");
    process.exit(1);
  }
  console.log("\nPARITY TEST PASSED.");
}

main();
